name: llm_algo_cnb_dev
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - ipywidgets
  - nbformat
  - nbconvert
  - jupyterlab-mathjax3
  - matplotlib
  - pandas
  - pip:
      - torch
      - einops
      - transformers
      - triton
      - termcolor
      - pytest
